spring:
  profiles:
    active: local
  application:
    name: incial- backend


  datasource:
    url: ${ENV_DB_URL}
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

# ===========================
# JWT Configuration
# ===========================
jwt:
  secret: ${ENV_JWT_SECRET}

# ===========================
# Logging
# ===========================
logging:
  level:
    com.incial.crm: DEBUG
    org.springframework.security: DEBUG

# ===========================
# Swagger Configuration
# ===========================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
